import { icons } from "@/constants/icon";

export const tabs: AppTab[] = [
    { name: "index", title: "Home", icon: icons.home },
    { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
    { name: "insights", title: "Insights", icon: icons.activity },
    { name: "settings", title: "Settings", icon: icons.setting },
];

export const HOME_USER = {
    name: "Isaac Ekaro",
};

export const HOME_BALANCE = {
    amount: 2489.48,
    nextRenewalDate: "2026-09-17T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "adobe-creative-cloud",
        icon: icons.adobe,
        name: "Adobe Creative Cloud",
        plan: "Teams Plan",
        category: "Design",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-03-20T10:00:00.000Z",
        price: 36.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-09-14T10:00:00.000Z",
        color: "#f5c542",
    },
    {
        id: "github-pro",
        icon: icons.github,
        name: "GitHub Pro",
        plan: "Developer",
        category: "Developer Tools",
        paymentMethod: "Mastercard ending in 2408",
        status: "active",
        startDate: "2024-11-24T10:00:00.000Z",
        price: 32.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-09-15T16:00:00.000Z",
        color: "#e8def8",
    },
    {
        id: "notion-plus",
        icon: icons.notion,
        name: "Notion",
        plan: "Plus",
        category: "Productivity",
        paymentMethod: "Visa ending in 4412",
        status: "active",
        startDate: "2025-01-16T12:00:00.000Z",
        price: 24.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-09-16T12:00:00.000Z",
        color: "#f6eecf",
    },
    {
        id: "spotify-premium",
        icon: icons.spotify,
        name: "Spotify",
        plan: "Premium",
        category: "Music",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-02-17T09:00:00.000Z",
        price: 40.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-09-17T09:00:00.000Z",
        color: "#c8e6c9",
    },
    {
        id: "figma-pro",
        icon: icons.figma,
        name: "Figma",
        plan: "Professional",
        category: "Design",
        paymentMethod: "Mastercard ending in 2408",
        status: "active",
        startDate: "2025-05-18T11:00:00.000Z",
        price: 35.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-09-18T11:00:00.000Z",
        color: "#fce4ec",
    },
    {
        id: "dropbox-plus",
        icon: icons.dropbox,
        name: "Dropbox",
        plan: "Plus",
        category: "Storage",
        paymentMethod: "Amex ending in 1010",
        status: "active",
        startDate: "2025-04-19T14:00:00.000Z",
        price: 22.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-09-19T14:00:00.000Z",
        color: "#bbdefb",
    },
    {
        id: "openai-plus",
        icon: icons.openai,
        name: "ChatGPT Plus",
        plan: "Plus",
        category: "AI Tools",
        paymentMethod: "Visa ending in 7784",
        status: "active",
        startDate: "2025-06-20T08:00:00.000Z",
        price: 25.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-09-20T08:00:00.000Z",
        color: "#d7ccc8",
    },
    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude",
        plan: "Pro Plan",
        category: "AI Tools",
        paymentMethod: "Amex ending in 1010",
        status: "active",
        startDate: "2025-06-25T12:00:00.000Z",
        price: 9.84,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-25T12:00:00.000Z",
        color: "#f5c542",
    },
    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva",
        plan: "Pro",
        category: "Design",
        paymentMethod: "Visa ending in 7784",
        status: "active",
        startDate: "2025-06-30T16:00:00.000Z",
        price: 43.89,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-06-30T16:00:00.000Z",
        color: "#8fd1bd",
    },
];